### ISSUE TITLE
Define the screens of the app and create a small design for them

### ISSUE THREAD

**Issue by fknives** [fknives/KeeyManager#6]
**Describe the solution you'd like**
There is no design for the application yet, it would be nice to see how it should actually look like. From that new issues should be created regarding the specific screens.

**Comment by kr1szt1** [comment]
Based on what we discussed, I tried to collect all the screens we need and come up with a design. I shared the design with you in Figma, please review it and feel free to add any comment or edit it. If I didn’t miss anything the app will have the features from below, the screens for these are included in the design.

Authentication:
- selecting database
- login with password (setup password)
- login with biometric authentication
Entry:
- show/edit entry details (username, password, URL, notes, last modified)
- show/edit/delete entry related data (name and icon)
- delete entry
Group:
- show group details (list of other groups and entries in the group)
- show/edit/delete group related data (name and icon)
- delete group
- search in group (by username and entry/group name)

**Comment by kr1szt1** [comment]
Design: https://www.figma.com/file/0to2FZr27jEwPH87JFZgfS/KeyManager?node-id=1011%3A3346.
